FROM php:8.2-apache

COPY ./src/attacker /var/www/html/

RUN apt-get update && \
    apt-get install -y libpcre3-dev gcc make autoconf && \
    pecl install sync && \
    docker-php-ext-enable sync

RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html

USER www-data

EXPOSE 80