services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: mysql_php_apache_web
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: mysql_php_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: sql_injection_in_pagination_clauses_database
      MARIADB_USER: sql_injection_in_pagination_clauses
      MARIADB_PASSWORD: passw0rd
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s