services:
  vulnerable-web:
    build:
      context: .
      dockerfile: Dockerfile.vulnerable-web
    ports:
      - "80:80"

  attacker-web:
    build:
      context: .
      dockerfile: Dockerfile.attacker-web
    ports:
      - "81:80"